--Spring Security

DROP TABLE IF EXISTS USERS CASCADE;
CREATE TABLE USERS(
USERNAME VARCHAR(255) NOT NULL UNIQUE,
PASSWORD VARCHAR(255) NOT NULL,
ENABLED SMALLINT NOT NULL DEFAULT 1
);


DROP TABLE IF EXISTS USER_ROLES CASCADE;
DROP SEQUENCE IF EXISTS USER_ROLE_SEQ;

CREATE SEQUENCE USER_ROLE_SEQ;
CREATE TABLE USER_ROLES(
USER_ROLE_ID INTEGER NOT NULL DEFAULT NEXTVAL('USER_ROLE_SEQ'),
USERNAME  VARCHAR(45) NOT NULL,
ROLE  VARCHAR(45) NOT NULL
);


--Main Tables
DROP TABLE IF EXISTS USERS_DETAILS CASCADE;
DROP SEQUENCE IF EXISTS USER_ID_SEQ;

CREATE SEQUENCE USER_ID_SEQ;
CREATE TABLE USERS_DETAILS(
USER_ID INT PRIMARY KEY NOT NULL DEFAULT NEXTVAL('USER_ID_SEQ'),
USERNAME VARCHAR(255) NOT NULL UNIQUE REFERENCES USERS(USERNAME),
USERIMG BYTEA,
FIRSTNAME VARCHAR(255) NOT NULL,
MIDDLENAME VARCHAR(255) NULL,
LASTNAME VARCHAR(255)  NULL,
ADDRESS VARCHAR
);

DROP TABLE IF EXISTS  REGISTERED_USERS CASCADE;
DROP SEQUENCE IF EXISTS REG_ID_SEQ;

CREATE SEQUENCE REG_ID_SEQ;
CREATE TABLE REGISTERED_USERS(
REGISTERED_ID INT PRIMARY KEY NOT NULL DEFAULT NEXTVAL('REG_ID_SEQ'),
REGISTRATION_DATE DATE NOT NULL,
REGISTRATION_NUMBER VARCHAR(255) NOT NULL,
USER_ID INT REFERENCES USERS_DETAILS(USER_ID)
);


DROP TABLE IF EXISTS  QUESTIONS CASCADE;
DROP SEQUENCE IF EXISTS QUES_ID_SEQ;

CREATE SEQUENCE QUES_ID_SEQ;
CREATE TABLE QUESTIONS(
QUESTION_ID INT PRIMARY KEY NOT NULL DEFAULT NEXTVAL('QUES_ID_SEQ'),
QUES_TEXT VARCHAR NOT NULL,
QUES_OP1 VARCHAR NOT NULL,
QUES_OP2 VARCHAR NOT NULL,
QUES_OP3 VARCHAR NOT NULL,
QUES_OP4 VARCHAR NOT NULL,
CORRECT_OPS VARCHAR NOT NULL,
QUES_MRKS INT NOT NULL
);





CREATE EXTENSION fuzzystrmatch;